import React, { useState, useRef, useCallback } from 'react';
import * as THREE from 'three';
import { Header } from './components/Header';
import { ControlBar } from './components/ControlBar';
import { Viewer } from './components/Viewer';
import { LoginPage } from './components/LoginPage';
import { SignUpPage } from './components/SignUpPage';
import { Toast } from './components/Toast';
import { DrawingCanvas } from './components/DrawingCanvas';
import type { PipelineStatus } from './types';
import { PipelineStage } from './types';

// This is the geometry format our backend returns
type GeneratedGeometry = {
  vertices: number[];
  faces: number[];
  uvs?: number[];
  accuracyScore?: number;
  accuracyJustification?: string;
};

export type WorkflowStep = 'upload' | 'generating' | 'results';
type AuthScreen = 'login' | 'signup';
// We keep this type for the ControlBar, but won't use it for API calls
export type ModelId = 'gemini-2.5-pro' | 'gemini-2.5-flash';


const App: React.FC = () => {
  const [isAuthenticated, setIsAuthenticated] = useState<boolean>(true); // Skip login for faster testing
  const [authScreen, setAuthScreen] = useState<AuthScreen>('login');
  const [sketchFile, setSketchFile] = useState<File | null>(null);
  const [isDrawing, setIsDrawing] = useState<boolean>(false);
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [workflowStep, setWorkflowStep] = useState<WorkflowStep>('upload');
  const [pipelineStatus, setPipelineStatus] = useState<PipelineStatus>({
    currentStage: null,
    completedStages: new Set(),
  });
  const [generatedGeometries, setGeneratedGeometries] = useState<GeneratedGeometry[]>([]);
  const [selectedGeometryIndex, setSelectedGeometryIndex] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [sketchPreview, setSketchPreview] = useState<string | null>(null);
  const modelRef = useRef<THREE.Group>(null!);

  // --- Simplified State for TripoSR ---
  // We remove state for options our new backend doesn't support
  const [textPrompt, setTextPrompt] = useState<string>('');
  
  // These are no longer used by the API, but the ControlBar
  // might still show them. We can remove them from ControlBar later.
  const [numberOfVariations, setNumberOfVariations] = useState<number>(1);
  const [generateUVs, setGenerateUVs] = useState<boolean>(false);
  const [selectedModel, setSelectedModel] = useState<ModelId>('gemini-2.5-pro');
  const [creativityLevel, setCreativityLevel] = useState<number>(20);


  const handleFileChange = (file: File | null) => {
    if (file) {
      setSketchFile(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setSketchPreview(reader.result as string);
      };
      reader.readAsDataURL(file);
      handleResetVariations();
      setWorkflowStep('generating');
    }
  };

  const handleGeneration = async () => {
    if (!sketchFile) {
      setError("Please upload a sketch first.");
      return;
    }

    // !!! PASTE YOUR NGROK URL HERE
    // It will look like: https://kim-dilemmic-overtrustfully.ngrok-free.dev
    const BACKEND_URL = "YOUR_NGROK_PUBLIC_URL_HERE/generate-mesh/";

    if (BACKEND_URL.includes("YOUR_NGROK_PUBLIC_URL_HERE")) {
        setError("Please update the BACKEND_URL in App.tsx with your ngrok URL.");
        return;
    }

    setIsGenerating(true);
    setError(null);
    setGeneratedGeometries([]);
    setSelectedGeometryIndex(null);
    setWorkflowStep('generating');
    
    // Set a simple status for the user
    setPipelineStatus({ currentStage: PipelineStage.TRAINING, completedStages: new Set() });

    try {
      // 1. Create FormData to send the file
      const formData = new FormData();
      formData.append("file", sketchFile, sketchFile.name);

      // 2. Call your Colab backend
      const response = await fetch(BACKEND_URL, {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        throw new Error(`Backend Error: ${response.statusText} ${await response.text()}`);
      }

      const result = await response.json();
      
      if (result.error) {
        throw new Error(`Generation Error: ${result.error}`);
      }

      if (!result.vertices || !result.faces) {
        throw new Error("The model failed to return valid 3D data.");
      }

      // 3. Set the geometry from the response
      // We only get one variation from this model
      const geometry: GeneratedGeometry = {
        vertices: result.vertices,
        faces: result.faces,
        // We can skip the accuracy check for this custom model
        accuracyScore: 100, 
        accuracyJustification: "Generated by TripoSR"
      };
      
      setGeneratedGeometries([geometry]);
      setSelectedGeometryIndex(0);
      setWorkflowStep('results');
      setPipelineStatus({ currentStage: null, completedStages: new Set(Object.values(PipelineStage)) });

    } catch (e) {
      console.error(e);
      setError(`Generation Error: ${e instanceof Error ? e.message : String(e)}`);
      setPipelineStatus({ currentStage: null, completedStages: new Set() });
      setWorkflowStep(sketchFile ? 'generating' : 'upload');
    } finally {
      setIsGenerating(false);
    }
  };


  const handleStartOver = useCallback(() => {
    setSketchFile(null);
    setSketchPreview(null);
    setWorkflowStep('upload');
    handleResetVariations();
  }, []);

  const handleResetVariations = useCallback(() => {
    setIsGenerating(false);
    setPipelineStatus({ currentStage: null, completedStages: new Set() });
    setGeneratedGeometries([]);
    setSelectedGeometryIndex(null);
    setError(null);
    // We keep the text prompt
    // setTextPrompt(''); 
    if (sketchFile) {
      setWorkflowStep('generating');
    }
  }, [sketchFile]);

  const saveFile = (blob: Blob, filename: string) => {
    const link = document.createElement('a');
    link.style.display = 'none';
    document.body.appendChild(link);
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    link.click();
    URL.revokeObjectURL(link.href);
    document.body.removeChild(link);
  };

  const handleExportOBJ = () => {
    const geoData = selectedGeometryIndex !== null ? generatedGeometries[selectedGeometryIndex] : null;

    if (!geoData || !geoData.vertices || !geoData.faces) {
        setError("Error: No exportable mesh data found.");
        return;
    }
    
    const { vertices, faces, uvs } = geoData;
    
    let output = '# Generated by Sketch-to-3D Mesh AI (TripoSR)\n';
    
    for (let i = 0; i < vertices.length; i += 3) {
        output += `v ${vertices[i].toFixed(6)} ${vertices[i+1].toFixed(6)} ${vertices[i+2].toFixed(6)}\n`;
    }
    
    if (uvs) {
        for (let i = 0; i < uvs.length; i += 2) {
            output += `vt ${uvs[i].toFixed(6)} ${uvs[i+1].toFixed(6)}\n`;
        }
    }

    output += `g object_1\n` // Add a group name
    output += `s 1\n` // Smoothing group

    for (let i = 0; i < faces.length; i += 3) {
        const i1 = faces[i] + 1;
        const i2 = faces[i + 1] + 1;
        const i3 = faces[i + 2] + 1;
        if (uvs) {
            output += `f ${i1}/${i1} ${i2}/${i2} ${i3}/${i3}\n`;
        } else {
            // Standard face definition v/vt/vn. We only have v.
            output += `f ${i1} ${i2} ${i3}\n`;
        }
    }
    
    saveFile(new Blob([output], { type: 'text/plain' }), `model_variation_${(selectedGeometryIndex ?? 0) + 1}.obj`);
  };

  const handleLogin = () => setIsAuthenticated(true);
  const navigateToSignUp = () => setAuthScreen('signup');
  const navigateToLogin = () => setAuthScreen('login');
  
  const handleToggleDrawing = () => setIsDrawing(prev => !prev);
  
  const handleDrawingComplete = (file: File) => {
    handleFileChange(file);
    setIsDrawing(false);
  };

  const selectedGeometry = selectedGeometryIndex !== null ? generatedGeometries[selectedGeometryIndex] : null;

  if (!isAuthenticated) {
    if (authScreen === 'login') return <LoginPage onLogin={handleLogin} onNavigateToSignUp={navigateToSignUp} />;
    return <SignUpPage onNavigateToLogin={navigateToLogin} onSignUpSuccess={handleLogin}/>;
  }

  return (
    <div className="flex flex-col h-screen font-sans bg-base-100 text-content antialiased">
      <Header />
      {isDrawing && <DrawingCanvas onComplete={handleDrawingComplete} onCancel={handleToggleDrawing} />}
      <main className="flex-1 relative">
        <Viewer 
          geometry={selectedGeometry} 
          isGenerating={isGenerating}
          pipelineStatus={pipelineStatus}
          modelRef={modelRef} 
        />
        <ControlBar
          onFileChange={handleFileChange}
          onGenerate={handleGeneration}
          onToggleDrawing={handleToggleDrawing}
          isGenerating={isGenerating}
          pipelineStatus={pipelineStatus}
          sketchPreview={sketchPreview}
          onExportOBJ={handleExportOBJ}
          onResetVariations={handleResetVariations}
          onStartOver={handleStartOver}
          // Pass down the simplified/dummy state
          numberOfVariations={numberOfVariations}
          onNumberOfVariationsChange={setNumberOfVariations}
          generateUVs={generateUVs}
          onGenerateUVsChange={setGenerateUVs}
          textPrompt={textPrompt}
          onTextPromptChange={setTextPrompt}
          selectedModel={selectedModel}
          onSelectedModelChange={setSelectedModel}
          creativityLevel={creativityLevel}
          onCreativityLevelChange={setCreativityLevel}
          
          generatedGeometries={generatedGeometries}
          selectedVariationIndex={selectedGeometryIndex}
          onSelectVariation={setSelectedGeometryIndex}
          workflowStep={workflowStep}
        />
      </main>
      <Toast message={error} onDismiss={() => setError(null)} />
    </div>
  );
};

export default App;